# User configurations for orbital-radar

[prepare]

[prepare.airborne]
mean_flight_velocity = 60

[prepare.general]
height_min = -2500
height_max = 17500
height_res = 10
ground_echo_ze_max = 52
ground_echo_pulse_length = 100

[prepare.groundbased]
mean_wind = 6
